name: Laravel Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    - name: Copy .env
      run: cp .env.example .env
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Execute tests via Pest
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: ":memory:"
        APP_PEPPER: "SWSklucz2026!@"
      run: vendor/bin/pest